version: '3.8'

services:
  # Production service
  fast-embedding:
    build:
      context: .
      target: production
    image: fast-embedding:latest
    container_name: fast-embedding-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # API Configuration
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
      - LOG_LEVEL=INFO
      
      # Required Models
      - REQUIRED_MODELS=BAAI/bge-small-en-v1.5,BAAI/bge-base-en-v1.5,sentence-transformers/all-MiniLM-L6-v2
      
      # Performance Settings
      - THREAD_POOL_WORKERS=4
      - MAX_TEXT_LENGTH=8192
      - MAX_BATCH_SIZE=32
      - REQUEST_TIMEOUT=300
      
      # Cache Settings
      - MODEL_CACHE_TTL=3600
      - MAX_CACHED_MODELS=5
      - CLEANUP_INTERVAL=60
      
      # Security (configure for production)
      - ENABLE_CORS=true
      - CORS_ORIGINS=*
      - ENABLE_RATE_LIMIT=false
      - RATE_LIMIT_REQUESTS=100
      
      # Monitoring
      - ENABLE_METRICS=true
    volumes:
      # Persist model cache
      - model_cache:/app/.cache/fastembed
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G

  # Development service (optional)
  fast-embedding-dev:
    build:
      context: .
      target: development
    image: fast-embedding:dev
    container_name: fast-embedding-dev
    ports:
      - "8001:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - ENABLE_METRICS=true
    volumes:
      # Mount source code for hot reload
      - .:/app
      # Persist model cache
      - model_cache_dev:/app/.cache/fastembed
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    profiles:
      - dev

volumes:
  model_cache:
    driver: local
  model_cache_dev:
    driver: local

# Production deployment with multiple replicas (optional)
# Uncomment and configure for high availability
#
# services:
#   fast-embedding-ha:
#     build:
#       context: .
#       target: production
#     image: fast-embedding:latest
#     restart: unless-stopped
#     environment:
#       # ... same as above
#     volumes:
#       - model_cache:/app/.cache/fastembed
#     deploy:
#       mode: replicated
#       replicas: 3
#       resources:
#         limits:
#           cpus: '2'
#           memory: 2G
#   
#   nginx:
#     image: nginx:alpine
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     depends_on:
#       - fast-embedding-ha
